apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
resources:
# repo: bitnami-labs/sealed-secrets
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.4/controller.yaml

patches:
- ./resources.patch.yaml
