apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: sealed-secrets-controller
          image: docker.io/bitnami/sealed-secrets-controller:0.32.2
          resources:
            requests:
              cpu: 30m
---
