apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ./namespace.yaml
# repo: argoproj/argo-cd
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.1/manifests/install.yaml
- ./apps.yaml

patches:
- ./configmap.patch.yaml
- ./resources.patch.yaml
