name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go mod download
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: production
          cloud-url: "s3://k8s.social-stackbackend?endpoint=objectstore.lon1.civo.com&s3ForcePathStyle=true&region=LON1"
          comment-on-pr: true
        env:
          AWS_ACCESS_KEY_ID=${{ secrets.STACK_BACKEND_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.STACK_BACKEND_SECRET_ACCESS_KEY }}
          PULUMI_CONFIG_PASSPHRASE=${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
